# Generated by Django 5.2.6 on 2025-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='preview_url',
            field=models.URLField(blank=True, help_text='URL where the deployed project can be accessed', null=True),
        ),
    ]
