# Generated by Django 5.2.6 on 2025-09-24 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='deployment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='build_log',
            new_name='log',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='port',
            new_name='exposed_port',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_url',
            new_name='github_repo_url',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='commit_message',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_token',
        ),
        migrations.AddField(
            model_name='deployment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('running', 'Running'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'db_table': 'projects_tags',
                'unique_together': {('project', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', through='core.ProjectTag', to='core.tag'),
        ),
    ]
