# Generated by Django 5.2.6 on 2025-09-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_alter_deployment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build_command',
            field=models.CharField(blank=True, help_text='Custom build command if needed', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='docker_container_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='docker_image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='dockerfile_path',
            field=models.CharField(default='Dockerfile', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='environment_variables',
            field=models.TextField(blank=True, help_text='JSON format environment variables'),
        ),
        migrations.AddField(
            model_name='project',
            name='run_command',
            field=models.CharField(blank=True, help_text='Custom run command if needed', max_length=200),
        ),
    ]
