# Generated by Django 5.2.6 on 2025-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_build_command_project_docker_container_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtoken',
            name='github_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
