# Generated by Django 5.2.6 on 2025-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_githubtoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='webhook_branch',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='webhook_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
