# Generated by Django 5.2.6 on 2025-09-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_webhook_branch_project_webhook_enabled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildCache',
        ),
    ]
