# Generated by Django 5.2.6 on 2025-09-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_buildcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_username',
        ),
    ]
