# Generated by Django 5.2.6 on 2025-09-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_linkedin_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentVariable',
        ),
    ]
