# Generated by Django 5.2.6 on 2025-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_drop_allauth_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='container_port',
            field=models.IntegerField(default=80, help_text='Container internal port (default: 80)'),
        ),
    ]
